sudo: false
language: php
cache:
  directories:
    - $HOME/.composer/cache
    - build/vendor
    - node_modules
php:
  - 5.6
install:
   - nvm install stable
   # install `pa11y`
   - npm install
   - npm install phantomjs-prebuilt
   - npm install pa11y
   - npm install grunt-cli
   - npm install http-server
   # build the templates
   - ./node_modules/.bin/grunt
   # import test dependencies
   - cd build
   - composer install --prefer-source
   - cd ../
script:
  # start a localhost server on 8080 for the root
  - nohup node_modules/.bin/http-server -d false -r >/dev/null &
  - phpunit tests
branches:
  only:
    - develop
