sudo: false
language: php
cache:
  directories:
    - $HOME/.composer/cache
    - build/vendor
    - node_modules
php:
  - 5.6
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
install:
  - nvm install stable
  - npm install
  # install `pa11y`
  - npm install phantomjs-prebuilt pa11y http-server grunt-cli
  # build the templates
  - ./node_modules/.bin/grunt
  # import test dependencies
  - cd build
  - composer install --prefer-source
  - cd ../
script:
  # start a localhost server on 8080 for the root
  - nohup node_modules/.bin/http-server -d false -r >/dev/null &
  - phpunit tests
branches:
  only:
    - develop
