language: php
php:
  - 5.4
before_install:
   # configure apache virtual hosts
   - sudo apt-get update
   - sudo apt-get install apache2
   - sudo apt-get install php5-curl
   - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
   - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
   - sudo a2enmod include
   - sudo a2enmod headers
   - sudo apachectl configtest
   - sudo service apache2 restart
before_script: 
   # install `pa11y`
   - npm install
   - npm install pa11y
   - npm install grunt-cli
   # build the templates
   - ./node_modules/grunt-cli/bin/grunt
   # import test dependencies
   - cd build
   - composer install --prefer-source
   - cd ../
script: ./tests/run-tests.sh
branches:
  only:
    - develop
    - accessibility-tests
