language: php
php:
  - 5.4
before_install:
   # configure apache virtual hosts
   - sudo apt-get update
   - sudo apt-get install apache2
   - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
   - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
   - sudo service apache2 restart
before_script: 
   - pyrus install -p pyrus.net/Pyrus_Developer-alpha && make
   # install dependancies for `make`
   - npm install -g requirejs
   - npm install -g less
   - npm install -g uglify-js
   # install `pa11y`
   - npm install pa11y
   # build the templates
   - make
   # import test dependencies
   - composer install --prefer-source
   # make `#!/usr/bin/env node` work -- used in pa11y
   - sudo ln -s `which nodejs` /usr/local/bin/node
   - which node
   - echo $PATH
script: pyrus run-phpt -r tests || (find . -name *.out | xargs -t cat && exit 1)
branches:
  only:
    - develop
    - accessibility-tests
